version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
#    env_file: .env
    environment:
      - POSTGRES_DB=keiser
      - POSTGRES_USER=henswurst
      - POSTGRES_PASSWORD=password1234
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/create_tables.sql

#  ohlcv-service:
#    build:
#      context: .
#      dockerfile: ./ohlcv/Dockerfile
#    image: ticker_save
#    volumes:
#      - ./output:/app/output